### DISCUSSION TITLE
Color the card (not the tag)

### DISCUSSION THREAD

**Discussion by reneverkaart** [roovo/obsidian-card-board#152] [General]
Hi, I've added the snippet you placed on your code page. It works fine, but only for the tag on the card. Like this:
![CardBoard color snippet_01](https://user-images.githubusercontent.com/66939481/234896427-83bce819-5f81-4493-9c30-83edf50540ec.png)

Since I don't want to show the tag on the card, I'd like to change the colour of the line on the left of the card. This:
![CardBoard color snippet_02](https://user-images.githubusercontent.com/66939481/234896972-4779dd2c-cf02-4036-9fa3-c9980cb5b039.png)

I'm sure I'm missing something since I'm not a programmer. Could you tell me what I'm doing wrong, or help me with a snippet of how I can change the line on the left of the card?

Thanks in advance.

**Comment by daladim** [comment]
After a quick look, this color depends on the due date of the task.
Past due dates are colored using `var(--text-error)` (which happens to be red), today are `var(--text-success)`, soon to be due are `var(--text-accent)`.

However, that would be great to
* have a way to override/customize these colors (I quickly tried to re-define these variables in `.obsidian/plugins/card-board/styles.css` in my valut, with no sucess, even with an `!important` value)
* have a way to choose colors depending on other criteria than just due date (tags?)

**Comment by roovo** [comment]
Hiya

I'm afraid that for the moment Cardboard only chooses colors based on due dates.  You are not the first to ask this and it is a feature it would be good to support (the good news), but it will be a while out as my priority is to get drag and drop working and this is a pretty mamouth task! (the bad news).

In the meantime, you should be able to use a css snippet along these lines to customise the colours:

```css
.card-board-view .card-board-card-highlight-area.critical {
  background-color: red;
}

.card-board-view .card-board-card-highlight-area.good {
  background-color: green;
}

.card-board-view .card-board-card-highlight-area.important {
  background-color: orange;
}
```

I may actually be able to push a feature that would let you set custom colors (via css snippets) based on tags.  Leave it with me to have a think/investigate...
