### DISCUSSION TITLE
change the style of text-decoration of task list

### DISCUSSION THREAD

**Discussion by chienyutseng** [roovo/obsidian-card-board#163] [Q&A]
I encountered an issue where I wanted to change the text-decoration line style of the task list from line-through to underline after checking the checkbox. I attempted to address this by adding a CSS style to the plugin's .css file, but unfortunately, the line-through style persisted.

Here is the CSS rule I added:

**.card-board-card input.task-list-item-checkbox:checked + .card-board-card-title {
  color: red;
  text-decoration-line: underline;
  text-decoration-color: cyan;
}**

**Comment by roovo** [comment]
this should do the trick:

```css
.card-board-card-title del {
  color: red;
  text-decoration-line: underline;
  text-decoration-color: cyan;
}
```
