### ISSUE TITLE
Feature Request- UI option to change color indicators in Dated board

### ISSUE THREAD

**Issue by davebhc71** [roovo/obsidian-card-board#131]
Would like to change colors for Past and Current items. Orange and Red are too similar!😉

**Comment by roovo** [comment]
thanks btw :)

**Comment by davebhc71** [comment]
Just to follow up on this FR - Green for Today would be nice. And, I’m not asking for the User to be able to change the color, but that you consider a ‘universal’ change for Today to Green in the next update. 😉

**Comment by roovo** [comment]
Just realised that you should be able to use a css snippet along these lines to customise the colours:

```css
.card-board-view .card-board-card-highlight-area.critical {
  background-color: red;
}

.card-board-view .card-board-card-highlight-area.good {
  background-color: green;
}

.card-board-view .card-board-card-highlight-area.important {
  background-color: orange;
}
```
